### ISSUE TITLE
DoubleScrollbar.js missing

### ISSUE THREAD

**Issue by appukuttan-shailesh** [material-table-core/core#528] opened 2022-04-13 09:38 UTC
Same as ticket in parent repo: https://github.com/mbrn/material-table/issues/3111

Getting this error:
```
WARNING in ./node_modules/react-double-scrollbar/dist/DoubleScrollbar.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/shailesh/gits/collab-file-cloner/collab-file-cloner/node_modules/react-double-scrollbar/dist/DoubleScrollbar.js.map' file: Error: ENOENT: no such file or directory, open '/home/shailesh/gits/collab-file-cloner/collab-file-cloner/node_modules/react-double-scrollbar/dist/DoubleScrollbar.js.map'
 @ ./node_modules/@material-table/core/dist/components/MTableScrollbar/index.js 14:51-84
 @ ./node_modules/@material-table/core/dist/components/index.js 141:46-74
 @ ./node_modules/@material-table/core/dist/index.js 114:18-41
 @ ./src/LoadCollabs.js 16:0-68 107:43-56 145:49-62
 @ ./src/App.js 9:0-40 570:47-58
 @ ./src/index.js 9:0-24 17:37-40
```

Versions (package-lock.json):
 >       "@material-table/core": "^4.3.39",
 >       "@material-ui/core": "^4.12.4",

Installed via:
```
npm install @material-ui/core
npm install @material-table/core
```

**Comment by Domino987** [comment] 2022-04-13 21:02
Duplicate of #467

**Closed as completed by Domino987** 2022-04-13 21:02 UTC
Labels: bug
