### ISSUE TITLE
Drag and Drop columns after hiding columns shows dragged column on wrong position.

### ISSUE THREAD

**Issue by chrisdie** [material-table-core/core#531] opened 2022-04-14 08:57 UTC
Demo: https://codesandbox.io/s/material-table-refresh-forked-q7sot5?

**To Reproduce**
In the demo are 7 columns. 
C1 till C7. If you hide C2 and C3, and then drag C7 on C5, it lands on position of C4. 
I could live with that, BUT:  in the onColumnDragged event you get the destination index of column C5 and not of C4.

This makes it difficult for us to reestablish the columns order from the saved drag and drop positions.

**Expected behavior**
column C7 will be shown on position of column C5 and not C4.

**Comment by chrisdie** [comment] 2022-04-14 15:53
found a workaround: https://codesandbox.io/s/material-table-refresh-forked-5eb4ps?file=/src/index.js
I need to set the columns again and for that to work correctly I have to delete a tableData object in the column-objects, which are set by the MaterialTable apparently :)

**Comment by Domino987** [comment] 2022-04-16 09:40
That is most likely caused by the recent changes we made to improve the dragging. Ill take a look.

**Comment by Domino987** [comment] 2022-04-18 21:23
All of this will be fixed with the next release. Probably tonight, maybe tomorrow. Thanks for finding this.

**Closed as completed by Domino987** 2022-04-18 21:23 UTC
Labels: bug
