### ISSUE TITLE
Check and prevent duplicate values

### ISSUE THREAD

**Issue by DewangS** [material-table-core/core#522] opened 2022-04-01 04:03 UTC
Would it be possible to introduce a UNIQUE property for column(s) which can auto check and prevent duplicate values?

**Comment by Domino987** [comment] 2022-04-01 06:40
It is most likely possible. Would you mind creating a PR to address this?
I am sure could also be achieved using the validation honestly. Would you share a sandbox with your setup?

**Comment by DewangS** [comment] 2022-04-01 09:22
@Domino987 will do.

**Comment by Domino987** [comment] 2022-04-05 14:50
Duplicate of #520

**Closed as completed by Domino987** 2022-04-05 14:50 UTC
