### ISSUE TITLE
Uncaught TypeError: (0 , _deepmergeTs.deepmerge) is not a function     at LocalizationStore.js:44:1

### ISSUE THREAD

**Issue by MojtabaDaneshi1366** [material-table-core/core#636] opened 2022-10-04 13:12 UTC
Hello,

I got this error:
Uncaught TypeError: (0 , _deepmergeTs.deepmerge) is not a function
    at LocalizationStore.js:44:1

My App was ok, but today is get this error.

@material-table/core@**next**

Sicnerely

**Comment by Domino987** [comment] 2022-10-04 15:43
Can you reproduce this in a sandbox ?

**Comment by Domino987** [comment] 2022-10-05 09:41
Duplicate of #586

**Closed as completed by Domino987** 2022-10-05 09:41 UTC
Labels: bug
