### ISSUE TITLE
parentChildData and selection issue

### ISSUE THREAD

**Issue by nathanm960** [material-table-core/core#606] opened 2022-08-24 09:07 UTC
Hello,

I have an issue with parentChildData and selection.

I made a codesandbox to reproduce https://codesandbox.io/s/material-table-starter-template-forked-woh93u?file=/src/index.js

 **How reproduce**

Go on the sandbox and type "test" in the search field.

You should have one row displayed.

Now click on the global checkbox to select all visible rows.

The checkbox is indeterminate.

 **What is expected**

We expect the checkbox to be selected because all visible rows are selected.

The problem come from parentChildData because if you remove it everything work properly.

**Comment by Domino987** [comment] 2022-09-07 06:56
Thanks for finding this.
It will be fixed with 5.1.1

**Closed as completed by Domino987** 2022-09-07 06:56 UTC
Labels: bug

**Comment by nathanmichel** [comment] 2022-11-21 13:23
Hello,

It seems to have a new issue with this fix (it appear in 5.1.1). The issue is also in 0.2.54

I updated the codesandbox : https://codesandbox.io/s/material-table-starter-template-forked-woh93u?file=/src/index.js

**How reproduce**

Go on the sandbox and click on the global checkbox

Every row are selected but not the global checkbox

The global checkbox is not clickable anymore  

\
The issue appear when there is at least one parentId in data

**What is expected**

The global checkbox should be selected and clickable
